project:
  type: website
  output-dir: docs

website:
  title: "Leo's Long Covid Journey"
  navbar:
    right:
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

