project:
  type: website
  output-dir: docs

website:
  title: "Leo's Long Covid Blog"
  site-url: https://leonidliu.github.io/long_covid_blog/
  description: "A blog chronicling Leo's journey with Long Covid, with a dash of data"
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

